-- MySQL Script generated by MySQL Workbench
-- mar 07 jul 2020 12:11:16 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Amazon
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Amazon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Amazon` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `Amazon` ;

-- -----------------------------------------------------
-- Table `Amazon`.`Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Amazon`.`Autor` (
  `id_autor` INT NOT NULL AUTO_INCREMENT,
  `direccio` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id_autor`),
  UNIQUE INDEX `id_autor_UNIQUE` (`id_autor` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Amazon`.`Usuari`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Amazon`.`Usuari` (
  `id_usuari` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `contrasenya` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuari`),
  UNIQUE INDEX `id_usuari_UNIQUE` (`id_usuari` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Amazon`.`Cataleg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Amazon`.`Cataleg` (
  `id_cataleg` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_cataleg`),
  UNIQUE INDEX `id_cataleg_UNIQUE` (`id_cataleg` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Amazon`.`Llibre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Amazon`.`Llibre` (
  `id_llibre` INT NOT NULL AUTO_INCREMENT,
  `titol` VARCHAR(45) NOT NULL,
  `unitats` INT NOT NULL,
  `preu` FLOAT NOT NULL,
  `autor_id` INT NULL,
  `cataleg_id` INT NULL,
  PRIMARY KEY (`id_llibre`),
  UNIQUE INDEX `id_llibre_UNIQUE` (`id_llibre` ASC) ,
  INDEX `fk_Llibre_Autor_idx` (`autor_id` ASC) ,
  INDEX `fk_Llibre_Cataleg1_idx` (`cataleg_id` ASC) ,
  CONSTRAINT `fk_Llibre_Autor`
    FOREIGN KEY (`autor_id`)
    REFERENCES `Amazon`.`Autor` (`id_autor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Llibre_Cataleg1`
    FOREIGN KEY (`cataleg_id`)
    REFERENCES `Amazon`.`Cataleg` (`id_cataleg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Amazon`.`Comanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Amazon`.`Comanda` (
  `id_comanda` INT NOT NULL AUTO_INCREMENT,
  `usuari_id` INT NOT NULL,
  `llibre_id` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `data` DATE NOT NULL,
  PRIMARY KEY (`id_comanda`),
  UNIQUE INDEX `id_factura_UNIQUE` (`id_comanda` ASC) ,
  INDEX `fk_Comanda_Llibre1_idx` (`llibre_id` ASC) ,
  INDEX `fk_Comanda_Usuari1_idx` (`usuari_id` ASC) ,
  CONSTRAINT `fk_Comanda_Llibre1`
    FOREIGN KEY (`llibre_id`)
    REFERENCES `Amazon`.`Llibre` (`id_llibre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comanda_Usuari1`
    FOREIGN KEY (`usuari_id`)
    REFERENCES `Amazon`.`Usuari` (`id_usuari`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Amazon`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Amazon`.`Factura` (
  `id_factura` INT NOT NULL AUTO_INCREMENT,
  `usuari_id` INT NOT NULL,
  `comanda_id` INT NOT NULL,
  `data` DATE NOT NULL,
  PRIMARY KEY (`id_factura`),
  UNIQUE INDEX `id_comanda_UNIQUE` (`id_factura` ASC) ,
  INDEX `fk_Factura_Usuari1_idx` (`usuari_id` ASC) ,
  INDEX `fk_Factura_Comanda1_idx` (`comanda_id` ASC) ,
  CONSTRAINT `fk_Factura_Usuari1`
    FOREIGN KEY (`usuari_id`)
    REFERENCES `Amazon`.`Usuari` (`id_usuari`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_Comanda1`
    FOREIGN KEY (`comanda_id`)
    REFERENCES `Amazon`.`Comanda` (`id_comanda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
