-- MySQL Script generated by MySQL Workbench
-- dom 05 jul 2020 22:43:01 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Optica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Optica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Optica` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `Optica` ;

-- -----------------------------------------------------
-- Table `Optica`.`Proveidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica`.`Proveidor` (
  `id_proveidor` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `carrer` VARCHAR(45) NOT NULL,
  `numero` INT(10) NOT NULL,
  `pis` INT(10) NOT NULL,
  `porta` VARCHAR(45) NOT NULL,
  `ciutat` VARCHAR(50) NOT NULL,
  `codi_postal` INT(20) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `tel` INT(50) NOT NULL,
  `fax` INT(50) NOT NULL,
  `nif` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id_proveidor`),
  UNIQUE INDEX `id_proveidor_UNIQUE` (`id_proveidor` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica`.`Empleat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica`.`Empleat` (
  `id_empleat` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_empleat`),
  UNIQUE INDEX `id_empleat_UNIQUE` (`id_empleat` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica`.`Ulleres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica`.`Ulleres` (
  `id_ulleres` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NOT NULL,
  `graduacio1` FLOAT NOT NULL,
  `graduacio2` FLOAT NOT NULL,
  `tp_montura` VARCHAR(45) NOT NULL,
  `color_montura` VARCHAR(45) NOT NULL,
  `color_vidre1` VARCHAR(45) NOT NULL,
  `color_vidre2` VARCHAR(45) NOT NULL,
  `preu` FLOAT NOT NULL,
  `empleat_id` INT NULL,
  `proveidor_id` INT NOT NULL,
  PRIMARY KEY (`id_ulleres`),
  UNIQUE INDEX `id_ulleres_UNIQUE` (`id_ulleres` ASC) ,
  UNIQUE INDEX `proveidor_id_UNIQUE` (`proveidor_id` ASC) ,
  INDEX `fk_Ulleres_Empleat1_idx` (`empleat_id` ASC) ,
  CONSTRAINT `fk_Ulleres_Proveidor`
    FOREIGN KEY (`proveidor_id`)
    REFERENCES `Optica`.`Proveidor` (`id_proveidor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ulleres_Empleat1`
    FOREIGN KEY (`empleat_id`)
    REFERENCES `Optica`.`Empleat` (`id_empleat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica`.`Client` (
  `id_client` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `adresa` VARCHAR(45) NOT NULL,
  `tel` INT(50) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `data` DATE NOT NULL,
  `referit_client` INT NULL,
  PRIMARY KEY (`id_client`),
  UNIQUE INDEX `id_client_UNIQUE` (`id_client` ASC) )
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
