-- MySQL Script generated by MySQL Workbench
-- sáb 04 jul 2020 11:19:26 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Quadres
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Quadres
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Quadres` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `Quadres` ;

-- -----------------------------------------------------
-- Table `Quadres`.`Comprador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Quadres`.`Comprador` (
  `id_comprador` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL,
  `cognom` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL,
  `dni` VARCHAR(9) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL,
  PRIMARY KEY (`id_comprador`),
  UNIQUE INDEX `id_comprador_UNIQUE` (`id_comprador` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `Quadres`.`Quadre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Quadres`.`Quadre` (
  `id_quadre` INT NOT NULL AUTO_INCREMENT,
  `preu` INT(255) NOT NULL,
  `autor` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL,
  `comprador_id` INT NOT NULL,
  PRIMARY KEY (`id_quadre`),
  UNIQUE INDEX `id_quadre_UNIQUE` (`id_quadre` ASC),
  INDEX `fk_Quadre_Comprador_idx` (`comprador_id` ASC),
  CONSTRAINT `fk_Quadre_Comprador`
    FOREIGN KEY (`comprador_id`)
    REFERENCES `Quadres`.`Comprador` (`id_comprador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
