-- MySQL Script generated by MySQL Workbench
-- sáb 04 jul 2020 11:15:41 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Stube
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Stube
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Stube` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `Stube` ;

-- -----------------------------------------------------
-- Table `Stube`.`Usuari`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Stube`.`Usuari` (
  `id usuari` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(50) NOT NULL,
  `contrasenya` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id usuari`),
  UNIQUE INDEX `id usuari_UNIQUE` (`id usuari` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `Stube`.`Video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Stube`.`Video` (
  `id_video` INT NOT NULL AUTO_INCREMENT,
  `descripcio` TEXT(300) NOT NULL,
  `titol` VARCHAR(50) NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  `identificador` VARCHAR(50) NOT NULL,
  `usuari_id` INT NOT NULL,
  PRIMARY KEY (`id_video`),
  UNIQUE INDEX `id_video_UNIQUE` (`id_video` ASC),
  INDEX `fk_Video_Usuari_idx` (`usuari_id` ASC),
  CONSTRAINT `fk_Video_Usuari`
    FOREIGN KEY (`usuari_id`)
    REFERENCES `Stube`.`Usuari` (`id usuari`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
