-- MySQL Script generated by MySQL Workbench
-- dom 05 jul 2020 22:31:53 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Xarxa_Social
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Xarxa_Social
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Xarxa_Social` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `Xarxa_Social` ;

-- -----------------------------------------------------
-- Table `Xarxa_Social`.`Usuari`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Xarxa_Social`.`Usuari` (
  `id_usuari` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `contrasenya` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuari`),
  UNIQUE INDEX `id_usuari_UNIQUE` (`id_usuari` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Xarxa_Social`.`Foto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Xarxa_Social`.`Foto` (
  `id_foto` INT NOT NULL AUTO_INCREMENT,
  `lloc` VARCHAR(255) NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  `usuari_id` INT NOT NULL,
  PRIMARY KEY (`id_foto`),
  UNIQUE INDEX `id_foto_UNIQUE` (`id_foto` ASC) ,
  INDEX `fk_Foto_Usuari_idx` (`usuari_id` ASC) ,
  CONSTRAINT `fk_Foto_Usuari`
    FOREIGN KEY (`usuari_id`)
    REFERENCES `Xarxa_Social`.`Usuari` (`id_usuari`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Xarxa_Social`.`Amic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Xarxa_Social`.`Amic` (
  `id_amic` INT NOT NULL AUTO_INCREMENT,
  `usuari1_id` INT NOT NULL,
  `usuari2_id` INT NOT NULL,
  PRIMARY KEY (`id_amic`),
  UNIQUE INDEX `id_amic_UNIQUE` (`id_amic` ASC) ,
  INDEX `fk_Amic_Usuari1_idx` (`usuari1_id` ASC) ,
  INDEX `fk_Amic_Usuari2_idx` (`usuari2_id` ASC) ,
  CONSTRAINT `fk_Amic_Usuari1`
    FOREIGN KEY (`usuari1_id`)
    REFERENCES `Xarxa_Social`.`Usuari` (`id_usuari`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Amic_Usuari2`
    FOREIGN KEY (`usuari2_id`)
    REFERENCES `Xarxa_Social`.`Usuari` (`id_usuari`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
